version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - uploads_data:/app/uploads # Mount the uploads directory
    depends_on:
      - redis
      - qdrant

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    # volumes:
    #   - redis_data:/data

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC
    # volumes:
    #   - qdrant_data:/qdrant/storage

volumes:
  uploads_data:
  redis_data: # Persistent Redis storage
  qdrant_data: # Persistent Qdrant storage
